"""init-12

Revision ID: 020c5cb260aa
Revises: 9490ccd65be6
Create Date: 2026-02-08 02:22:55.327933

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "020c5cb260aa"
down_revision = "9490ccd65be6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("casino_orden", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_casino_orden_menu_id_casino_menu_dia"), type_="foreignkey")
        batch_op.drop_column("menu_id")

    with op.batch_alter_table("casino_seleccion_orden", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_casino_seleccion_orden_orden_id_casino_orden"),
            type_="foreignkey",
        )
        batch_op.drop_column("orden_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("casino_seleccion_orden", schema=None) as batch_op:
        batch_op.add_column(sa.Column("orden_id", sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(
            batch_op.f("fk_casino_seleccion_orden_orden_id_casino_orden"),
            "casino_orden",
            ["orden_id"],
            ["id"],
        )

    with op.batch_alter_table("casino_orden", schema=None) as batch_op:
        batch_op.add_column(sa.Column("menu_id", sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(
            batch_op.f("fk_casino_orden_menu_id_casino_menu_dia"),
            "casino_menu_dia",
            ["menu_id"],
            ["id"],
        )

    # ### end Alembic commands ###
