"""init-9

Revision ID: 18fce6b6bad5
Revises: f7d3909fb2fc
Create Date: 2026-02-07 22:09:54.460006

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "18fce6b6bad5"
down_revision = "f7d3909fb2fc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("casino_menu_dia", schema=None) as batch_op:
        batch_op.add_column(sa.Column("es_permanente", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("activo", sa.Boolean(), nullable=True))

    with op.batch_alter_table("casino_opcion_menu_dia", schema=None) as batch_op:
        batch_op.alter_column(
            "tipo_curso",
            existing_type=sa.VARCHAR(length=11),
            type_=sa.Enum("ENTRADA", "FONDO", "POSTRE", name="tipocurso"),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("casino_opcion_menu_dia", schema=None) as batch_op:
        batch_op.alter_column(
            "tipo_curso",
            existing_type=sa.Enum("ENTRADA", "FONDO", "POSTRE", name="tipocurso"),
            type_=sa.VARCHAR(length=11),
            existing_nullable=False,
        )

    with op.batch_alter_table("casino_menu_dia", schema=None) as batch_op:
        batch_op.drop_column("activo")
        batch_op.drop_column("es_permanente")

    # ### end Alembic commands ###
