"""check

Revision ID: 1c659aae9e49
Revises: e1f2a3b4c5d6
Create Date: 2026-03-08 16:23:40.497808

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "1c659aae9e49"
down_revision = "e1f2a3b4c5d6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("_alembic_tmp_casino_apoderado")
    with op.batch_alter_table("casino_apoderado", schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f("uq_casino_apoderado_usuario_id"), ["usuario_id"])

    with op.batch_alter_table("merchants_payment", schema=None) as batch_op:
        batch_op.add_column(sa.Column("email", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("extra_args", sa.JSON(), nullable=False, server_default=sa.text("'{}'")))
        batch_op.add_column(sa.Column("provider_payment_object", sa.JSON(), nullable=False, server_default=sa.text("'{}'")))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("merchants_payment", schema=None) as batch_op:
        batch_op.drop_column("provider_payment_object")
        batch_op.drop_column("extra_args")
        batch_op.drop_column("email")

    with op.batch_alter_table("casino_apoderado", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_casino_apoderado_usuario_id"), type_="unique")

    op.create_table(
        "_alembic_tmp_casino_apoderado",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("nombre", sa.VARCHAR(length=255), nullable=False),
        sa.Column("alumnos_registro", sa.INTEGER(), nullable=True),
        sa.Column("usuario_id", sa.INTEGER(), nullable=False),
        sa.Column("comprobantes_transferencia", sa.BOOLEAN(), nullable=False),
        sa.Column("notificacion_compra", sa.BOOLEAN(), nullable=False),
        sa.Column("informe_semanal", sa.BOOLEAN(), nullable=False),
        sa.Column("tag_compartido", sa.BOOLEAN(), nullable=False),
        sa.Column("copia_notificaciones", sa.VARCHAR(length=255), nullable=True),
        sa.Column("maximo_diario", sa.INTEGER(), nullable=True),
        sa.Column("maximo_semanal", sa.INTEGER(), nullable=True),
        sa.Column("saldo_cuenta", sa.INTEGER(), nullable=True),
        sa.Column("limite_notificacion", sa.INTEGER(), nullable=False),
        sa.Column("created", sa.DATETIME(), nullable=False),
        sa.Column("updated", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(["usuario_id"], ["user.id"], name=op.f("fk_casino_apoderado_usuario_id_user")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_casino_apoderado")),
        sa.UniqueConstraint("usuario_id", name=op.f("uq_casino_apoderado_usuario_id")),
    )
    # ### end Alembic commands ###
