"""init-3

Revision ID: 2e47724a9982
Revises: f74f3bc5d558
Create Date: 2026-02-07 01:16:20.284825

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = "2e47724a9982"
down_revision = "f74f3bc5d558"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "casino_plato_imagen",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("archivo", sa.String(length=255), nullable=False),
        sa.Column("plato_id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plato_id"],
            ["casino_plato.id"],
            name=op.f("fk_casino_plato_imagen_plato_id_casino_plato"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_casino_plato_imagen")),
        sa.UniqueConstraint("archivo", name=op.f("uq_casino_plato_imagen_archivo")),
    )
    with op.batch_alter_table("casino_plato", schema=None) as batch_op:
        batch_op.drop_column("imagenes")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("casino_plato", schema=None) as batch_op:
        batch_op.add_column(sa.Column("imagenes", sqlite.JSON(), nullable=True))

    op.drop_table("casino_plato_imagen")
    # ### end Alembic commands ###
