"""check

Revision ID: 37b3743f0968
Revises: a7b8c9d0e1f2
Create Date: 2026-03-08 19:12:08.275814

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "37b3743f0968"
down_revision = "a7b8c9d0e1f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("merchants_payment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_merchants_payment_session_id"))
        batch_op.create_index(batch_op.f("ix_merchants_payment_merchants_id"), ["merchants_id"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("merchants_payment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_merchants_payment_merchants_id"))
        batch_op.create_index(batch_op.f("ix_merchants_payment_session_id"), ["merchants_id"], unique=1)

    # ### end Alembic commands ###
