"""init-13

Revision ID: 3839fc86dfcf
Revises: 020c5cb260aa
Create Date: 2026-02-08 02:23:21.796895

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3839fc86dfcf"
down_revision = "020c5cb260aa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("casino_seleccion_orden")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "casino_seleccion_orden",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("opcion_id", sa.INTEGER(), nullable=False),
        sa.Column("plato_nombre", sa.VARCHAR(length=255), nullable=False),
        sa.Column("tipo_curso", sa.VARCHAR(length=7), nullable=False),
        sa.Column("cantidad", sa.INTEGER(), nullable=False),
        sa.Column("notas", sa.VARCHAR(length=255), nullable=True),
        sa.Column("created", sa.DATETIME(), nullable=False),
        sa.Column("updated", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["opcion_id"],
            ["casino_opcion_menu_dia.id"],
            name=op.f("fk_casino_seleccion_orden_opcion_id_casino_opcion_menu_dia"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_casino_seleccion_orden")),
    )
    # ### end Alembic commands ###
