"""init-7

Revision ID: 3a2c99e54bfc
Revises: f4a641ca06c2
Create Date: 2026-02-07 03:03:08.540617

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3a2c99e54bfc"
down_revision = "f4a641ca06c2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("casino_foto_plato", schema=None) as batch_op:
        batch_op.drop_column("nombre")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("casino_foto_plato", schema=None) as batch_op:
        batch_op.add_column(sa.Column("nombre", sa.VARCHAR(length=64), nullable=False))

    # ### end Alembic commands ###
