"""Stock MenuDiario

Revision ID: 3e09568495e7
Revises: a472a74ad0df
Create Date: 2026-02-21 19:11:47.078600

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "3e09568495e7"
down_revision = "a472a74ad0df"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("casino_menu_dia", schema=None) as batch_op:
        batch_op.add_column(sa.Column("stock", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("fuera_stock", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("casino_menu_dia", schema=None) as batch_op:
        batch_op.drop_column("fuera_stock")
        batch_op.drop_column("stock")

    # ### end Alembic commands ###
