"""updates

Revision ID: 5bfc4fdbefb4
Revises: e1f2a3b4c5d6
Create Date: 2026-03-08 21:28:19.658240

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5bfc4fdbefb4"
down_revision = "e1f2a3b4c5d6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("merchants_payment", schema=None) as batch_op:
	# Rename session_id -> merchants_id
        batch_op.alter_column("session_id", new_column_name="merchants_id")

        batch_op.add_column(sa.Column("transaction_id", sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column("email", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("extra_args", sa.JSON(), server_default=sa.text("'{}'"), nullable=False))
        batch_op.add_column(sa.Column("payment_object", sa.JSON(), server_default=sa.text("'{}'"), nullable=False))
        batch_op.alter_column(
            "currency", existing_type=sa.VARCHAR(length=8), type_=sa.String(length=3), existing_nullable=False
        )
        batch_op.drop_index(batch_op.f("ix_merchants_payment_session_id"))
        #batch_op.create_index(batch_op.f("ix_merchants_payment_email"), ["email"], unique=False)
        #batch_op.create_index(batch_op.f("ix_merchants_payment_merchants_id"), ["merchants_id"], unique=True)
        #batch_op.create_index(batch_op.f("ix_merchants_payment_provider"), ["provider"], unique=False)
        #batch_op.create_index(batch_op.f("ix_merchants_payment_state"), ["state"], unique=False)
        #batch_op.create_index(batch_op.f("ix_merchants_payment_transaction_id"), ["transaction_id"], unique=True)
        batch_op.drop_column("redirect_url")

    # Backfill transaction_id from merchants_id for existing rows
    op.execute("UPDATE merchants_payment SET transaction_id = merchants_id WHERE transaction_id IS NULL")

    with op.batch_alter_table("merchants_payment", schema=None) as batch_op:
        # Now make transaction_id non-nullable
        batch_op.alter_column(
            "transaction_id",
            existing_type=sa.String(length=128),
            nullable=False,
        )
        # Create unique index on transaction_id
        batch_op.create_index(
            batch_op.f("ix_merchants_payment_transaction_id"),
            ["transaction_id"],
            unique=True,
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("merchants_payment", schema=None) as batch_op:
        # Drop new indexes
        batch_op.drop_index(batch_op.f("ix_merchants_payment_transaction_id"))
        batch_op.drop_index(batch_op.f("ix_merchants_payment_email"))
        batch_op.drop_index(batch_op.f("ix_merchants_payment_state"))
        batch_op.drop_index(batch_op.f("ix_merchants_payment_provider"))

        # Drop transaction_id column
        batch_op.drop_column("transaction_id")

        # Re-add redirect_url column
        batch_op.add_column(
            sa.Column("redirect_url", sa.String(length=2048), nullable=False, server_default="")
        )

        # Revert currency from String(3) to String(8)
        batch_op.alter_column(
            "currency",
            existing_type=sa.String(length=3),
            type_=sa.String(length=8),
            existing_nullable=False,
        )

        # Rename payment_object -> provider_payment_object
        batch_op.alter_column("payment_object", new_column_name="provider_payment_object")

        # Rename merchants_id -> session_id
        batch_op.alter_column("merchants_id", new_column_name="session_id")

        # Remove server_defaults from request_payload and response_payload
        batch_op.alter_column(
            "request_payload",
            existing_type=sa.JSON(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "response_payload",
            existing_type=sa.JSON(),
            server_default=None,
            existing_nullable=False,
        )
    # ### end Alembic commands ###
