"""init-15

Revision ID: 69b7ab61e5a3
Revises: 7ca93bc6b615
Create Date: 2026-02-11 00:26:40.762682

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "69b7ab61e5a3"
down_revision = "7ca93bc6b615"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("casino_apoderado", schema=None) as batch_op:
        batch_op.add_column(sa.Column("comprobantes_transferencia", sa.Boolean(), nullable=True, default=False))
        batch_op.add_column(sa.Column("notificacion_compra", sa.Boolean(), nullable=True, default=False))
        batch_op.add_column(sa.Column("informe_semanal", sa.Boolean(), nullable=True, default=False))
        batch_op.add_column(sa.Column("tag_compartido", sa.Boolean(), nullable=True, default=False))
        batch_op.add_column(sa.Column("copia_notificaciones", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("maximo_diario", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("maximo_semanal", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("casino_apoderado", schema=None) as batch_op:
        batch_op.drop_column("maximo_semanal")
        batch_op.drop_column("maximo_diario")
        batch_op.drop_column("copia_notificaciones")
        batch_op.drop_column("tag_compartido")
        batch_op.drop_column("informe_semanal")
        batch_op.drop_column("notificacion_compra")
        batch_op.drop_column("comprobantes_transferencia")

    # ### end Alembic commands ###
