"""init-14

Revision ID: 7ca93bc6b615
Revises: 3839fc86dfcf
Create Date: 2026-02-10 22:36:27.322884

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "7ca93bc6b615"
down_revision = "3839fc86dfcf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("casino_apoderado", schema=None) as batch_op:
        batch_op.add_column(sa.Column("alumnos_registro", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("casino_apoderado", schema=None) as batch_op:
        batch_op.drop_column("alumnos_registro")

    # ### end Alembic commands ###
