"""init-11

Revision ID: 9490ccd65be6
Revises: a9285953b117
Create Date: 2026-02-08 02:22:07.354349

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9490ccd65be6"
down_revision = "a9285953b117"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("casino_orden", schema=None) as batch_op:
        batch_op.add_column(sa.Column("codigo_merchants", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_casino_orden_codigo_merchants"),
            ["codigo_merchants"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("casino_orden", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_casino_orden_codigo_merchants"))
        batch_op.drop_column("codigo_merchants")

    # ### end Alembic commands ###
