"""init

Revision ID: a879adbfc59e
Revises:
Create Date: 2026-02-06 23:54:20.040401

"""

import flask_security
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a879adbfc59e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "casino_menu_dia",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dia", sa.Date(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("precio", sa.Numeric(precision=10, scale=0), nullable=True),
        sa.Column("descripcion", sa.String(length=2048), nullable=True),
        sa.Column("extra_attrs", sa.JSON(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_casino_menu_dia")),
        sa.UniqueConstraint("slug", name=op.f("uq_casino_menu_dia_slug")),
    )
    with op.batch_alter_table("casino_menu_dia", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_casino_menu_dia_dia"), ["dia"], unique=False)

    op.create_table(
        "casino_plato",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("es_vegano", sa.Boolean(), nullable=False),
        sa.Column("es_vegetariano", sa.Boolean(), nullable=False),
        sa.Column("es_hipocalorico", sa.Boolean(), nullable=False),
        sa.Column("contiene_gluten", sa.Boolean(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_casino_plato")),
    )
    op.create_table(
        "merchants_integrations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("integration_class", sa.String(length=255), nullable=True),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merchants_integrations")),
        sa.UniqueConstraint("slug", name=op.f("uq_merchants_integrations_slug")),
    )
    op.create_table(
        "merchants_payment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("merchants_token", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum("created", "processing", "declined", "cancelled", "refunded", "paid", name="paymentstatus"),
            nullable=False,
        ),
        sa.Column("integration_slug", sa.String(length=255), nullable=False),
        sa.Column("integration_transaction", sa.String(length=255), nullable=True),
        sa.Column("integration_payload", sa.JSON(), nullable=True),
        sa.Column("integration_response", sa.JSON(), nullable=True),
        sa.Column(
            "creation", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "last_update", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merchants_payment")),
        sa.UniqueConstraint("merchants_token", name=op.f("uq_merchants_payment_merchants_token")),
    )
    with op.batch_alter_table("merchants_payment", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_merchants_payment_integration_slug"), ["integration_slug"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_merchants_payment_integration_transaction"), ["integration_transaction"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_merchants_payment_status"), ["status"], unique=False)

    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("permissions", flask_security.datastore.AsaList(), nullable=True),
        sa.Column("update_datetime", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role")),
        sa.UniqueConstraint("name", name=op.f("uq_role_name")),
    )
    op.create_table(
        "user",
        sa.Column("fs_webauthn_user_handle", sa.String(length=64), nullable=True),
        sa.Column("mf_recovery_codes", flask_security.datastore.AsaList(), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("us_phone_number", sa.String(length=128), nullable=True),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("us_totp_secrets", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("fs_uniquifier", sa.String(length=64), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("current_login_at", sa.DateTime(), nullable=True),
        sa.Column("last_login_ip", sa.String(length=64), nullable=True),
        sa.Column("current_login_ip", sa.String(length=64), nullable=True),
        sa.Column("login_count", sa.Integer(), nullable=True),
        sa.Column("tf_primary_method", sa.String(length=64), nullable=True),
        sa.Column("tf_totp_secret", sa.String(length=255), nullable=True),
        sa.Column("tf_phone_number", sa.String(length=128), nullable=True),
        sa.Column("create_datetime", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("update_datetime", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("email", name=op.f("uq_user_email")),
        sa.UniqueConstraint("fs_uniquifier", name=op.f("uq_user_fs_uniquifier")),
        sa.UniqueConstraint("fs_webauthn_user_handle", name=op.f("uq_user_fs_webauthn_user_handle")),
        sa.UniqueConstraint("us_phone_number", name=op.f("uq_user_us_phone_number")),
        sa.UniqueConstraint("username", name=op.f("uq_user_username")),
    )
    op.create_table(
        "casino_apoderado",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["usuario_id"], ["user.id"], name=op.f("fk_casino_apoderado_usuario_id_user")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_casino_apoderado")),
    )
    op.create_table(
        "casino_foto_plato",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("nombre", sa.String(length=64), nullable=False),
        sa.Column("archivo", sa.String(length=255), nullable=False),
        sa.Column("plato_id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plato_id"], ["casino_plato.id"], name=op.f("fk_casino_foto_plato_plato_id_casino_plato")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_casino_foto_plato")),
        sa.UniqueConstraint("slug", name=op.f("uq_casino_foto_plato_slug")),
    )
    op.create_table(
        "casino_opcion_menu_dia",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("menu_id", sa.Integer(), nullable=False),
        sa.Column("plato_id", sa.Integer(), nullable=False),
        sa.Column(
            "tipo_curso", sa.Enum("ENTRADA", "FONDO", "POSTRE", "VEGETARIANO", name="tipocurso"), nullable=False
        ),
        sa.Column("orden", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["menu_id"], ["casino_menu_dia.id"], name=op.f("fk_casino_opcion_menu_dia_menu_id_casino_menu_dia")
        ),
        sa.ForeignKeyConstraint(
            ["plato_id"], ["casino_plato.id"], name=op.f("fk_casino_opcion_menu_dia_plato_id_casino_plato")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_casino_opcion_menu_dia")),
    )
    op.create_table(
        "roles_users",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], name=op.f("fk_roles_users_role_id_role")),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("fk_roles_users_user_id_user")),
    )
    op.create_table(
        "alumno",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("curso", sa.String(length=255), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("motivo", sa.String(length=255), nullable=True),
        sa.Column("apoderado_id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["apoderado_id"], ["casino_apoderado.id"], name=op.f("fk_alumno_apoderado_id_casino_apoderado")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alumno")),
        sa.UniqueConstraint("slug", name=op.f("uq_alumno_slug")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("alumno")
    op.drop_table("roles_users")
    op.drop_table("casino_opcion_menu_dia")
    op.drop_table("casino_foto_plato")
    op.drop_table("casino_apoderado")
    op.drop_table("user")
    op.drop_table("role")
    with op.batch_alter_table("merchants_payment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_merchants_payment_status"))
        batch_op.drop_index(batch_op.f("ix_merchants_payment_integration_transaction"))
        batch_op.drop_index(batch_op.f("ix_merchants_payment_integration_slug"))

    op.drop_table("merchants_payment")
    op.drop_table("merchants_integrations")
    op.drop_table("casino_plato")
    with op.batch_alter_table("casino_menu_dia", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_casino_menu_dia_dia"))

    op.drop_table("casino_menu_dia")
    # ### end Alembic commands ###
