"""init-10

Revision ID: a9285953b117
Revises: 18fce6b6bad5
Create Date: 2026-02-08 02:14:34.107228

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a9285953b117"
down_revision = "18fce6b6bad5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "casino_orden",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("codigo", sa.String(length=36), nullable=False),
        sa.Column("menu_id", sa.Integer(), nullable=False),
        sa.Column(
            "estado",
            sa.Enum(
                "CREADA",
                "PENDIENTE",
                "PAGADA",
                "ENVIADA",
                "CONFIRMADA",
                "ENTREGADA",
                "CANCELADA",
                name="estadoorden",
            ),
            nullable=False,
        ),
        sa.Column("fecha_orden", sa.DateTime(), nullable=False),
        sa.Column("fecha_entrega", sa.DateTime(), nullable=True),
        sa.Column("precio_total", sa.Numeric(precision=10, scale=0), nullable=False),
        sa.Column(
            "tipo_pago",
            sa.Enum("EFECTIVO", "TRANSFERENCIA", "TARJETA", name="tipopago"),
            nullable=False,
        ),
        sa.Column("pagado", sa.Boolean(), nullable=False),
        sa.Column("extra_attrs", sa.JSON(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["menu_id"],
            ["casino_menu_dia.id"],
            name=op.f("fk_casino_orden_menu_id_casino_menu_dia"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_casino_orden")),
        sa.UniqueConstraint("codigo", name=op.f("uq_casino_orden_codigo")),
    )
    with op.batch_alter_table("casino_orden", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_casino_orden_fecha_orden"), ["fecha_orden"], unique=False)

    op.create_table(
        "casino_seleccion_orden",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("orden_id", sa.Integer(), nullable=False),
        sa.Column("opcion_id", sa.Integer(), nullable=False),
        sa.Column("plato_nombre", sa.String(length=255), nullable=False),
        sa.Column(
            "tipo_curso",
            sa.Enum("ENTRADA", "FONDO", "POSTRE", name="tipocurso"),
            nullable=False,
        ),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column("notas", sa.String(length=255), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["opcion_id"],
            ["casino_opcion_menu_dia.id"],
            name=op.f("fk_casino_seleccion_orden_opcion_id_casino_opcion_menu_dia"),
        ),
        sa.ForeignKeyConstraint(
            ["orden_id"],
            ["casino_orden.id"],
            name=op.f("fk_casino_seleccion_orden_orden_id_casino_orden"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_casino_seleccion_orden")),
    )
    with op.batch_alter_table("casino_menu_dia", schema=None) as batch_op:
        batch_op.alter_column("activo", existing_type=sa.BOOLEAN(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("casino_menu_dia", schema=None) as batch_op:
        batch_op.alter_column("activo", existing_type=sa.BOOLEAN(), nullable=True)

    op.drop_table("casino_seleccion_orden")
    with op.batch_alter_table("casino_orden", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_casino_orden_fecha_orden"))

    op.drop_table("casino_orden")
    # ### end Alembic commands ###
