"""init-5

Revision ID: d69fad1d513c
Revises: 95446e2c53be
Create Date: 2026-02-07 02:14:40.839237

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d69fad1d513c"
down_revision = "95446e2c53be"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "casino_foto_plato",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("nombre", sa.String(length=64), nullable=False),
        sa.Column("archivo", sa.String(length=255), nullable=False),
        sa.Column("plato_id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plato_id"], ["casino_plato.id"], name=op.f("fk_casino_foto_plato_plato_id_casino_plato")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_casino_foto_plato")),
        sa.UniqueConstraint("slug", name=op.f("uq_casino_foto_plato_slug")),
    )
    op.drop_table("casino_plato_imagen")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "casino_plato_imagen",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("archivo", sa.VARCHAR(length=255), nullable=False),
        sa.Column("plato_id", sa.INTEGER(), nullable=False),
        sa.Column("created", sa.DATETIME(), nullable=False),
        sa.Column("updated", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plato_id"], ["casino_plato.id"], name=op.f("fk_casino_plato_imagen_plato_id_casino_plato")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_casino_plato_imagen")),
        sa.UniqueConstraint("archivo", name=op.f("uq_casino_plato_imagen_archivo")),
    )
    op.drop_table("casino_foto_plato")
    # ### end Alembic commands ###
