"""init-1

Revision ID: e3b49f2f7a6f
Revises: a879adbfc59e
Create Date: 2026-02-07 00:51:20.638237

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e3b49f2f7a6f"
down_revision = "a879adbfc59e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("casino_foto_plato")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "casino_foto_plato",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("slug", sa.VARCHAR(length=255), nullable=False),
        sa.Column("nombre", sa.VARCHAR(length=64), nullable=False),
        sa.Column("archivo", sa.VARCHAR(length=255), nullable=False),
        sa.Column("plato_id", sa.INTEGER(), nullable=False),
        sa.Column("created", sa.DATETIME(), nullable=False),
        sa.Column("updated", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plato_id"],
            ["casino_plato.id"],
            name=op.f("fk_casino_foto_plato_plato_id_casino_plato"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_casino_foto_plato")),
        sa.UniqueConstraint("slug", name=op.f("uq_casino_foto_plato_slug")),
    )
    # ### end Alembic commands ###
