"""init-6

Revision ID: f4a641ca06c2
Revises: d69fad1d513c
Create Date: 2026-02-07 02:16:17.132739

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f4a641ca06c2"
down_revision = "d69fad1d513c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("casino_foto_plato", schema=None) as batch_op:
        batch_op.alter_column("plato_id", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("casino_foto_plato", schema=None) as batch_op:
        batch_op.alter_column("plato_id", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###
