"""init-2

Revision ID: f74f3bc5d558
Revises: e3b49f2f7a6f
Create Date: 2026-02-07 01:01:36.525364

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f74f3bc5d558"
down_revision = "e3b49f2f7a6f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("casino_plato", schema=None) as batch_op:
        batch_op.add_column(sa.Column("imagenes", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("casino_plato", schema=None) as batch_op:
        batch_op.drop_column("imagenes")

    # ### end Alembic commands ###
