"""init-8

Revision ID: f7d3909fb2fc
Revises: 3a2c99e54bfc
Create Date: 2026-02-07 03:06:20.458301

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f7d3909fb2fc"
down_revision = "3a2c99e54bfc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("casino_foto_plato", schema=None) as batch_op:
        batch_op.add_column(sa.Column("nombre", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("casino_foto_plato", schema=None) as batch_op:
        batch_op.drop_column("nombre")

    # ### end Alembic commands ###
