import os
from flask import Blueprint, send_from_directory

_DOCS_DIR = os.path.join(os.path.dirname(__file__), "docs_site")

docs_bp = Blueprint("docs", __name__)


@docs_bp.route("/docs/", defaults={"filename": "index.html"})
@docs_bp.route("/docs/<path:filename>")
def docs(filename):
    """Serve the static operations-manual site generated by MkDocs."""
    # Serve directory URLs (e.g. /docs/faq/ -> faq/index.html)
    if not os.path.splitext(filename)[1]:
        filename = filename.rstrip("/") + "/index.html"
    return send_from_directory(_DOCS_DIR, filename)
