import os
from flask import Blueprint, abort, redirect, request, send_from_directory, url_for
from flask_security import current_user  # type: ignore

_DOCS_DIR = os.path.join(os.path.dirname(__file__), "docs_site")

docs_bp = Blueprint("docs", __name__)


def _is_admin_or_pos() -> bool:
    return current_user.is_active and current_user.is_authenticated and (
        current_user.has_role("admin") or current_user.has_role("pos")
    )


@docs_bp.route("/docs/", defaults={"filename": "index.html"})
@docs_bp.route("/docs/<path:filename>")
def docs(filename):
    """Serve the static operations-manual site generated by MkDocs.

    Pages under admin/ are restricted to admin and pos roles.
    """
    # Serve directory URLs (e.g. /docs/faq/ -> faq/index.html)
    if not os.path.splitext(filename)[1]:
        filename = filename.rstrip("/") + "/index.html"

    # Restrict the administrative section to admin and pos roles
    if filename.startswith("admin/"):
        if not current_user.is_authenticated:
            return redirect(url_for("security.login", next=request.url))
        if not _is_admin_or_pos():
            abort(403)

    return send_from_directory(_DOCS_DIR, filename)
